[package]
name = "input-router-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri = { version = "2", features = [] }
input-core = { path = "../../../crates/input-core" }
injector = { path = "../../../crates/injector" }
rdev = "0.5"
gilrs = "0.11.1"
serde = { version = "1", features = ["derive"] }

[build-dependencies]
tauri-build = { version = "2", features = [] }

[package.metadata]
tauri = {}
